import { Octokit } from '@octokit/rest';
import { config, labels } from './config.js';
import type { AiTask } from './types.js';

const octokit = new Octokit({ auth: config.GITHUB_TOKEN });

export async function doctorGithub(): Promise<void> {
  const repo = await octokit.repos.get({ owner: config.GITHUB_OWNER, repo: config.GITHUB_REPO });
  console.log(`GitHub OK: ${repo.data.full_name} default=${repo.data.default_branch}`);
}

export async function ensureLabels(): Promise<void> {
  for (const name of labels) {
    try {
      await octokit.issues.getLabel({ owner: config.GITHUB_OWNER, repo: config.GITHUB_REPO, name });
    } catch (err: any) {
      if (err.status !== 404) throw err;
      await octokit.issues.createLabel({
        owner: config.GITHUB_OWNER,
        repo: config.GITHUB_REPO,
        name,
        color: name.includes('jackhammer') ? '7057ff' : '0e8a16',
        description: name.includes('jackhammer') ? 'Queued by the GitHub Copilot JackHammer Service' : 'Generated by the GitHub Copilot JackHammer Service'
      });
    }
  }
}

export function renderIssue(task: AiTask, hash: string, commitSha: string): string {
  return `Generated by the GitHub Copilot JackHammer Service from repo context at commit \`${commitSha}\`.

> Queue hash: \`${hash}\`

## Summary
${task.summary}

## Copilot prompt
${task.copilot_prompt}

## Target files
${task.target_files.length ? task.target_files.map(f => `- \`${f}\``).join('\n') : '- Copilot should identify the files from the repo context.'}

## Acceptance criteria
${task.acceptance_criteria.map(x => `- [ ] ${x}`).join('\n')}

## Test plan
${task.test_plan.map(x => `- [ ] ${x}`).join('\n')}

## Risk notes
${task.risk_notes.length ? task.risk_notes.map(x => `- ${x}`).join('\n') : '- Keep changes small and reviewable.'}

## Human review required
Do not merge automatically. Open a PR and let the repository owner review the diff and CI result.
`;
}

export async function createIssue(task: AiTask, hash: string, commitSha: string): Promise<{ number: number; url: string }> {
  const title = `[JackHammer Queue][${task.priority}] ${task.title}`;
  const body = renderIssue(task, hash, commitSha);
  const assignees = config.COPILOT_ASSIGNEE ? [config.COPILOT_ASSIGNEE] : undefined;

  const issue = await octokit.issues.create({
    owner: config.GITHUB_OWNER,
    repo: config.GITHUB_REPO,
    title,
    body,
    labels,
    assignees
  });

  return { number: issue.data.number, url: issue.data.html_url };
}

export async function findExistingIssueByHash(hash: string): Promise<{ number: number; url: string } | null> {
  const q = `repo:${config.GITHUB_OWNER}/${config.GITHUB_REPO} ${hash} in:body is:issue`;
  const res = await octokit.search.issuesAndPullRequests({ q, per_page: 1 });
  const item = res.data.items[0];
  return item ? { number: item.number, url: item.html_url } : null;
}
